import 'package:cloud_firestore/cloud_firestore.dart';

class DataSeeder {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> seedData() async {
    try {
      // 1. Xóa dữ liệu cũ để tránh trùng lặp
      var oldItems = await _db.collection('menu_items').get();
      for (var doc in oldItems.docs) {
        await doc.reference.delete();
      }

      // 2. Danh sách 20 món ăn tiêu biểu
      List<Map<String, dynamic>> menuItems = [
        // --- MÓN CHÍNH ---
        {
          'itemId': 'item_01',
          'name': 'Phở Bò Tái Nạm Hà Nội',
          'description': 'Phở bò truyền thống với nước dùng xương hầm 24h, kèm thịt bò tái và nạm mềm.',
          'price': 65000.0,
          'imageUrl': 'https://vcdn1-dulich.vnecdn.net/2022/09/14/Pho-1-7459-1663154085.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bánh phở', 'Thịt bò', 'Hành lá', 'Nước dùng xương'],
        },
        {
          'itemId': 'item_02',
          'name': 'Bún Chả Hà Nội Đặc Biệt',
          'description': 'Thịt nướng than hoa thơm lừng, ăn kèm bún tươi và nước mắm chua ngọt đặc trưng.',
          'price': 60000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2017/03/21/963404/cach-lam-bun-cha-ha-noi-ngon-dam-da-dung-chuan-202206031405020164.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bún', 'Thịt lợn nướng', 'Nước mắm', 'Hành tỏi'],
        },
        {
          'itemId': 'item_03',
          'name': 'Cơm Tấm Sườn Bì Chả',
          'description': 'Sườn cốt lết nướng, bì heo trộn thính và chả trứng hấp, ăn cùng cơm tấm dẻo.',
          'price': 75000.0,
          'imageUrl': 'https://daotaobepvangg.com/wp-content/uploads/2020/09/com-tam-suon-bi-cha-chuan-vi-sai-gon.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Gạo tấm', 'Sườn heo', 'Bì thính', 'Chả trứng'],
        },
        {
          'itemId': 'item_04',
          'name': 'Bún Bò Huế Cố Đô',
          'description': 'Nước dùng đậm đà vị mắm ruốc, thơm mùi sả, kèm thịt bắp bò và giò heo.',
          'price': 70000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2020/05/22/1257457/cach-nau-bun-bo-hue-ngon-chuan-vi-tai-nha-cho-me-dam-dang-202206031505299444.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': true,
          'ingredients': ['Bún sợi to', 'Bắp bò', 'Mắm ruốc', 'Sả ớt'],
        },
        {
          'itemId': 'item_05',
          'name': 'Mì Quảng Tôm Thịt',
          'description': 'Món mì đặc trưng của Quảng Nam với nước dùng sền sệt, ăn kèm bánh tráng nướng.',
          'price': 55000.0,
          'imageUrl': 'https://vcdn-dulich.vnecdn.net/2022/09/16/Mi-Quang-7828-1663319086.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Mì Quảng', 'Tôm', 'Thịt lợn', 'Lạc rang'],
        },
        {
          'itemId': 'item_06',
          'name': 'Bún Riêu Cua Đồng',
          'description': 'Riêu cua thật 100%, nước dùng thanh ngọt từ cà chua, kèm đậu phụ và chả lụa.',
          'price': 50000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2020/06/15/1263057/cach-nau-bun-rieu-cua-ngon-chuan-vi-tai-nha-don-gian-va-hap-dan-202206031422003714.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bún', 'Cua đồng', 'Cà chua', 'Đậu phụ'],
        },
        {
          'itemId': 'item_07',
          'name': 'Hủ Tiếu Nam Vang Thập Cẩm',
          'description': 'Món hủ tiếu đa dạng nhân: tôm, gan, trứng cút và thịt bằm, nước dùng xương trong vắt.',
          'price': 65000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2021/08/11/1374521/hu-tieu-nam-vang-ngon-bat-tan-voi-cach-nau-cua-nguoi-hoa-tai-gia-202206031543301389.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Hủ tiếu', 'Tôm', 'Gan heo', 'Trứng cút'],
        },
        {
          'itemId': 'item_08',
          'name': 'Bò Kho Bánh Mì Đặc Biệt',
          'description': 'Bò hầm mềm trong nước sốt sánh mịn thơm mùi hồi và quế, ăn kèm bánh mì nóng giòn.',
          'price': 70000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2020/04/16/1249514/bi-quyet-nau-bo-kho-ngon-nhu-ngoai-hang-bang-goi-gia-vi-bo-kho-202206031411516541.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': true,
          'ingredients': ['Bò nạm', 'Cà rốt', 'Bánh mì', 'Gia vị bò kho'],
        },

        // --- KHAI VỊ & ĂN NHẸ ---
        {
          'itemId': 'item_09',
          'name': 'Gỏi Cuốn Tôm Thịt (4 Cuốn)',
          'description': 'Món ăn thanh mát với tôm, thịt luộc, rau thơm cuộn trong bánh tráng, chấm tương lạc.',
          'price': 40000.0,
          'imageUrl': 'https://vcdn-dulich.vnecdn.net/2022/09/14/Goi-cuon-4841-1663154086.jpg',
          'category': 'Khai vị',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Tôm', 'Thịt lợn', 'Rau thơm', 'Bánh tráng'],
        },
        {
          'itemId': 'item_10',
          'name': 'Chả Giò Sài Gòn Giòn Rụm',
          'description': 'Nhân thịt, mộc nhĩ, miến trộn đều, chiên vàng giòn rụm trong lớp vỏ bánh tráng.',
          'price': 45000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2019/12/30/1229094/cach-lam-cha-gio-sai-gon-vang-uom-gion-rum-ngon-kho-cuong-202206031448243166.jpg',
          'category': 'Khai vị',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Thịt băm', 'Mộc nhĩ', 'Miến', 'Bánh tráng'],
        },
        {
          'itemId': 'item_11',
          'name': 'Bánh Mì Hội An Thập Cẩm',
          'description': 'Bánh mì giòn rụm với nhân Pate gan, xá xíu, chả lụa và nước sốt bí truyền.',
          'price': 35000.0,
          'imageUrl': 'https://image.vtc.vn/resize/th/upload/2023/11/04/banh-mi-phuong-08311242.jpg',
          'category': 'Ăn nhẹ',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': true,
          'ingredients': ['Bánh mì', 'Pate', 'Xá xíu', 'Sốt bơ'],
        },
        {
          'itemId': 'item_12',
          'name': 'Bánh Xèo Nam Bộ Khổng Lồ',
          'description': 'Vỏ bánh vàng giòn tan, nhân tôm thịt và giá đỗ, ăn kèm rổ rau rừng phong phú.',
          'price': 85000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2018/12/12/1137452/cach-lam-banh-xeo-mien-tay-gion-ngon-it-dau-mo-202206031558237198.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bột gạo', 'Tôm', 'Thịt', 'Rau sống'],
        },
        {
          'itemId': 'item_13',
          'name': 'Bánh Khọt Vũng Tàu (8 Cái)',
          'description': 'Những chiếc bánh nhỏ giòn tan với nhân tôm tươi và mỡ hành thơm ngậy.',
          'price': 55000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2021/04/16/1343847/cach-lam-banh-khot-vung-tau-gion-rum-thom-ngon-chuan-vi-tai-nha-202206031548171052.jpg',
          'category': 'Khai vị',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bột gạo', 'Tôm', 'Mỡ hành', 'Nước mắm'],
        },
        {
          'itemId': 'item_14',
          'name': 'Bánh Cuốn Nóng Hành Phi',
          'description': 'Lớp vỏ mỏng mịn, nhân thịt băm mộc nhĩ thơm lừng hành phi thủ công.',
          'price': 40000.0,
          'imageUrl': 'https://vcdn1-dulich.vnecdn.net/2022/09/16/Banh-cuon-2975-1663319086.jpg',
          'category': 'Ăn nhẹ',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Bột gạo', 'Thịt băm', 'Mộc nhĩ', 'Hành phi'],
        },
        {
          'itemId': 'item_15',
          'name': 'Gà Xào Sả Ớt Miền Tây',
          'description': 'Gà thả vườn xào săn với sả băm và ớt cay nồng, đậm đà đưa cơm.',
          'price': 95000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2021/05/20/1353266/cach-lam-ga-xao-sa-ot-gion-ngon-cay-nong-dam-da-202206021611099684.jpg',
          'category': 'Món chính',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': true,
          'ingredients': ['Thịt gà', 'Sả', 'Ớt', 'Gia vị'],
        },
        {
          'itemId': 'item_16',
          'name': 'Nộm Hoa Chuối Tai Heo',
          'description': 'Món gỏi giòn sần sật với tai heo luộc và hoa chuối thái mỏng, chua ngọt hài hòa.',
          'price': 50000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2018/12/30/1141753/cach-lam-nom-hoa-chuoi-tai-heo-gion-ngon-ca-nha-deu-me-202206021644265492.jpg',
          'category': 'Khai vị',
          'isAvailable': true,
          'isVegetarian': false,
          'isSpicy': false,
          'ingredients': ['Hoa chuối', 'Tai heo', 'Lạc rang', 'Rau húng'],
        },

        // --- ĐỒ UỐNG & TRÁNG MIỆNG ---
        {
          'itemId': 'item_17',
          'name': 'Cà Phê Muối Đặc Sản',
          'description': 'Sự kết hợp hoàn hảo giữa vị đắng của cà phê và lớp kem muối béo mặn.',
          'price': 35000.0,
          'imageUrl': 'https://images2.thanhnien.vn/528068263637045248/2023/3/30/ca-phe-muoi-16801538356161989047910.jpg',
          'category': 'Đồ uống',
          'isAvailable': true,
          'isVegetarian': true,
          'isSpicy': false,
          'ingredients': ['Cà phê', 'Kem tươi', 'Muối biển', 'Sữa đặc'],
        },
        {
          'itemId': 'item_18',
          'name': 'Chè Ba Màu Truyền Thống',
          'description': 'Ly chè mát lạnh với đậu đỏ, đậu xanh và thạch lá dứa, phủ nước cốt dừa.',
          'price': 25000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2017/04/10/970725/cach-lam-che-ba-mau-thom-ngon-hap-dan-tai-nha-202206031535451994.jpg',
          'category': 'Tráng miệng',
          'isAvailable': true,
          'isVegetarian': true,
          'isSpicy': false,
          'ingredients': ['Đậu đỏ', 'Đậu xanh', 'Lá dứa', 'Cốt dừa'],
        },
        {
          'itemId': 'item_19',
          'name': 'Nước Ép Chanh Dây Mật Ong',
          'description': 'Giải nhiệt tức thì với vị chua thanh của chanh dây và ngọt dịu của mật ong.',
          'price': 30000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2021/05/24/1353982/cach-lam-nuoc-chanh-day-mat-ong-mat-lanh-tang-cuong-suc-de-khang-202206031518118029.jpg',
          'category': 'Đồ uống',
          'isAvailable': true,
          'isVegetarian': true,
          'isSpicy': false,
          'ingredients': ['Chanh dây', 'Mật ong', 'Đá viên'],
        },
        {
          'itemId': 'item_20',
          'name': 'Rau Má Đậu Xanh Sữa Dừa',
          'description': 'Nước rau má tươi kết hợp đậu xanh nghiền và cốt dừa béo ngậy.',
          'price': 30000.0,
          'imageUrl': 'https://cdn.tgdd.vn/Files/2020/06/17/1263595/cach-lam-rau-ma-dau-xanh-sua-dua-mat-lanh-giai-nhiet-cho-ngay-nang-nong-202206031534005953.jpg',
          'category': 'Đồ uống',
          'isAvailable': true,
          'isVegetarian': true,
          'isSpicy': false,
          'ingredients': ['Rau má', 'Đậu xanh', 'Cốt dừa'],
        },
      ];

      // Ghi dữ liệu vào Firestore
      for (var item in menuItems) {
        await _db.collection('menu_items').doc(item['itemId']).set(item);
      }
      
      print("✅ Đã cập nhật thực đơn 20 món thành công!");
    } catch (e) {
      print("❌ Lỗi khi nạp dữ liệu: $e");
    }
  }
}